### ISSUE TITLE
Not available！

### ISSUE THREAD

**Issue by GxYuqi** [EhsnJmli/ej_selector#1]
I followed the code copied directly from your Demo and called it in onPressed. There was no response and no log output, so this is an invalid library.

This is a screenshot of my code：
![image](https://user-images.githubusercontent.com/23255127/105572121-29080f80-5d90-11eb-804a-331fafe83b76.png)

**Comment by GxYuqi** [comment]
I want to execute a Dialog. Your library must be loaded before it can be used. It didn't help me. It is recommended to change to a dialog that can pop up at any time.

**Comment by EhsnJmli** [comment]
EJSelectorButton.string() is a factory which returns EJSelectorButton with type string.
EJSelectorButton is a widget it self with onPressed property.

You should use it as a widget, not call it in onPressed of another widget. 
Like this:
Container(
   child: EJSelectorButton.string(
      items: List.generate(10, (index) => 'item $index'),
      hint: 'Choose',
      useValue: false,
      divider: Divider(),
      textStyle: TextStyle(fontSize: 18),
      suffix: Icon(Icons.arrow_drop_down),
    ),
)

EJSelectorButton.string() has properties for customizing its button.

If you want to completely customize it use EJSelectorButton() instead of EJSelectorButton.string().

EJSelectorButton() has lots of properties for customizing, one of them is buttonBuilder and you can use it to create your button for EJSelectorButton().

Hope you enjoy it.

> I followed the code copied directly from your Demo and called it in onPressed. There was no response and no log output, so this is an invalid library.
> 
> This is a screenshot of my code：
> ![image](https://user-images.githubusercontent.com/23255127/105572121-29080f80-5d90-11eb-804a-331fafe83b76.png)

**Comment by EhsnJmli** [comment]
It is like DropdownButton() widget but shows dialog instead of dropdown and also has more properties and it is more customizable.

> I want to execute a Dialog. Your library must be loaded before it can be used. It didn't help me. It is recommended to change to a dialog that can pop up at any time.

**Comment by GxYuqi** [comment]
Thanks  !

**Comment by EhsnJmli** [comment]
Your welcome :)
